[opener]
edit = [{ run = 'nvim "$@"', block = true, desc = "Neovim" }]

reveal = [{ run = 'open -R "$1"', desc = "Reveal in Finder" }]

[open]
prepend_rules = [{ name = "*", use = ["reveal", "edit"] }]
